var GAME_LEVELS = [
 ["x   x                                                    x!!!!!!x                                            x",
   "x   x                                                    xx!!!!xx                                            x",
   "x   x                                                    xxx!!xxx                                            x",
   "x   x                          oooooo    o   o              !!              oooooooo         o    o          x",
   "x   x                          xxxxxx    x   x              |               xxxxxxxx         x    x    xxx o x",
   "x   x                                                        |                                           x   x",
   "x   x                                           o                        o                               x o x",
   "x @ x                                           x                        x            x!!!x              x   x",
   "x o x                                                                                 xxxxx              x o x",
   "x   x                                              o                  o                                  x   x",
   "x o x                                              x                  x                                  x o x",
   "x   x                                                                                                    x   x",
   "x o x                                                                                                    x o x",
   "x   x                                                 xxxxx  | xxxxx                                     x   x",
   "x o x                                                       |                                            x o x",
   "x   x                                                       !!                                           x   x",
   "x o x                                                       !!       xe             o  o  o  o  o  o  x       ",
   "x   x                               xxxxx     xxxxx     x!!!!!!!!x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "x o x                o                                  xxxxxxxxxx                                            ",
   "x   x            o       o                                                                                    ",
   "x o          xxxx         xxxxx                                                                               ",
   "x             oox                                                                             xxxxx           ",
   "x             oox                                                                                   ooo       ",
   "xxxxxxxxxx  xxxxx   xxxxx     xxxxx     xxxxx     xxxxx     xxxxxxxxx xxx xxx xxx xxx xxx xxx       xxx    x  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|!!!|!!!|!!!|!!!|!!!|!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxx |        |              ",
   "          ooooo                                         xxxxxxxxxxyyxxxxxxxxxxxxxxxxxxxxx |                       ",
   "        xxxxxxxxxxe    ooooo                                               xxxxxxxxxxxxxx               xxxx ooooo",
   "       xxxxxxyxxxxxxxxxxxxxxxxxxxxxe  ooooo                                             x        o  xxxxxxxxxooooo",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ooooo                             x       xxx xxxxxxxxxxxxyx",
   "| o |xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        o    o   o    x      xxxx xxxxxxyxxxxxxx",
   "!!x!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x     xxxxxxxxxxxxxxxxxxxx",
   "!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo                     x                         ",
   "!!!!!xxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo                        o   o   o    x| |      o    o    o     ",
   "x!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo                                       xxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxx      ",
   "!!!!x                                                                                                             ",
   "!!!!!                        o                                                              o     o    o    o     ",
   "!!!!!!                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!   o     o                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxx!xxxxxxxxxxxxxxxxyxxxxxx",
   "!!!!!!!!!  x     x                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxx!x!x!xxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxo                                      xxxxyxxxxxxxxxxx!xxxxxxxxxxxxxxyxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxo                                     x xxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxo                                            xxx",
   "!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxo                            xxx",
   "!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxo   xxx",
   "!!!!!!!!!xxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                            xxx",
   "!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxx                                             o            xxx",
   "x!!x!!x!!x     xxxxxxxxxxxxxxxxyxxxxxxx                                                 o       xxxxxxxxxxxxxxxxxx",
   "x||x||x||                                                             o   xxxxxxxxxxxxxxxx xxxxxxxxxxxxxxx!!!!!!!!",
   "                                                       o   xxxxxxxxxxxx!!!!!!xxxxxxxxyxxx! !xxxxxxxxxxxxxxxxxx!!!!",
   "         o     @                        o   xxxxxyxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!! !!xxxxxyxxxxxxxxxxxxx!!",
   "         x    xx            exxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxx!|!xxxxxxyxxxxxxxxxxxxxx!",
   "!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxxxxxxxx!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!!!!                                                                                                      !!!!",
   "!!!!                                                                                                      !!!!",  
   "!!!!                                                                                                      !!!!",  
   "!!!!                                               o                                                      !!!!",
   "!!!!      ooooo     ooooo     ooooo                                 ooooo       ooooo       ooooo         !!!!",
   "!!!!      xxxxx    =xxxxx    =xxxxx      x                   x      xxxxx      =xxxxx      =xxxxx         !!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                   o                                                          ",
   "                                                   x                                          = = = = = = = = ",
   "                     o                                                                                        ",
   "                     x                             o                                                          ",
   " = = = = = = = =                                   x e                                                 x    o ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxx",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                          x  ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x        xe e e                                                                               e e ex     xxxxx",
   "xx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!",
   "x        |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |          ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "xx                                                                                                            ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x          ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "                                                                             x                                ",
   "                                                                             x                                ",
   "                                                                             x                          x     ",
   "                                                                             x                          x   o ",
   "                                                                             x                          x   xx",
   "                                                                             x= =                   o   x    x",
   "   @  o                                        o  o  o  o  o  o  o  o  o     x                      xxxxxo   x",
   "  xxxxx                   xxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x            ||            xx   x",
   "  x                           x           x|                                 x            xx            x    x",
   "  x                           x           x                o                 x   o        ||         = =x   ox",
   "  x     xxxx         xxxx     xx          x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      x   xx",
   "  xx                         xx= = =      x                                  x                          x    x",
   "  x           xxxxx                       x                o                 x                          xo   x",
   "  x             x                  o o    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x    ooooooooooooooooo     xx   x",
   "  x                           x    xxx    x                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxx    x",
   "  xx                         xx           x                o                |x                          x   ox",
   "  x                           x!!x     x!!x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              xx",
   "  x e   o      o      o      ox!!x  o  x!!x                                 ooo   x               x          x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxx!!x   o          o          o             xe              xxxxxxxx   x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                    xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!xxxxxxxxx!!xxxxxxxxxx!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
